const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const FETCH_PRODUCT = "FETCH_PRODUCT";
const ADD_TO_CART = "ADD_TO_CART";
const BUY_NOW = "BUY_NOW";
const SET_LOADED = "SET_LOADED";
const SET_NOT_LOADED = "SET_NOT_LOADED";

export {
  FETCH_PRODUCTS,
  FETCH_PRODUCT,
  ADD_TO_CART,
  BUY_NOW,
  SET_LOADED,
  SET_NOT_LOADED,
};
